<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ToshibaPC" name="com.autotesting.framework.TestClass_1" tests="5" failures="1" timestamp="28 Jun 2014 18:40:27 GMT" time="24.704" errors="1">
  <testcase name="enterPassword" time="0.000" classname="com.autotesting.framework.TestClass_1"/>
  <testcase name="autarization" time="14.022" classname="com.autotesting.framework.TestClass_1"/>
  <testcase name="enterLogin" time="1.240" classname="com.autotesting.framework.TestClass_1">
    <error type="java.lang.AssertionError" message="Не совпадает e-mail указанный при регистрации expected [//*[text()=&#039;Вероника Забавская&#039;]] but found [Завести почту]">
      <![CDATA[java.lang.AssertionError: Не совпадает e-mail указанный при регистрации expected [//*[text()='Вероника Забавская']] but found [Завести почту]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.autotesting.framework.TestClass_1.enterLogin(TestClass_1.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- enterLogin -->
  <testcase name="notRightLogin" time="6.642" classname="com.autotesting.framework.TestClass_1"/>
  <testcase name="restablishPasswordAndLogin" time="2.800" classname="com.autotesting.framework.TestClass_1"/>
</testsuite> <!-- com.autotesting.framework.TestClass_1 -->
